baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Andy's Portfolio"
theme = "basic"

[params]
  author = "Andy Minn"
  description = "My portfolio website"

  gh_url = "https://api.github.com/users"
  gh_user = "andy-minn"